### ISSUE TITLE
请问修改防火墙设置对提升速度有用吗？

### ISSUE THREAD

**Issue by c1024** [iMeiji/shadowsocks_install#10]
在优化shadowsocks里面有提到修改防火墙配置。如下

自动调整MTU
iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

开启 NAT （记得把 eth0 改成自己的网卡名，openvz 的基本是 venet0 ）
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

开启 IPv4 的转发
sysctl -w net.ipv4.ip_forward=1

这个设置有效果吗？

**Comment by diaowenyang** [comment]
你好，请问你按照wiki的描述，可以翻墙成功吗？
