### ISSUE TITLE
用http post时如果使用自定义http header，请务必填写boundary是什么意思

### ISSUE THREAD

**Issue by cyj98** [iMeiji/shadowsocks_install#18]
ShadowsocksR 协议插件文档里面介绍http post混淆插件时说的，但看不懂是什么意思。

**Comment by iMeiji** [comment]
@cyj98 先搞懂 http 请求
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/POST
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Content-Type

**Comment by cyj98** [comment]
希望可以帮忙删除一下这个issue，谢谢。
