### ISSUE TITLE
shadowsocks Python 一键安装问题

### ISSUE THREAD

**Issue by panyuhang93** [iMeiji/shadowsocks_install#21]
好像有一个/etc/shadowsocks-python/config.json
和vi /etc/shadowsocks.json有什么关系吗？
./shadowsocks.sh uninstall我运行失败了

**Comment by daiedaie** [comment]
shadowsocks_install/shadowsocks.sh 安装脚本会自动生成/etc/shadowsocks.json:
```sh
# Config shadowsocks
function config_shadowsocks(){
    cat > /etc/shadowsocks.json<<-EOF
{
```
而一键安装脚本（https://raw.githubusercontent.com/iMeiji/shadowsocks_install/master/shadowsocks）自动生成的启动脚本(/etc/init.d/shadowsocks)中使用的配置文件也是`/etc/shadowsocks.json`:
```sh
name=shadowsocks
BIN=/usr/bin/ssserver
conf=/etc/shadowsocks.json

start(){
    $BIN -c $conf -d start
```

至于/etc/shadowsocks-python/config.json，可以忽略（估计你python版的shadowsocks安装在/etc/shadowsocks-python目录下，有可能是版本默认config）。
