### ISSUE TITLE
怎么翻墙

### ISSUE THREAD

**Issue by diaowenyang** [iMeiji/shadowsocks_install#28]
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh
chmod +x shadowsocksR.sh
./shadowsocksR.sh 2>&1 | tee shadowsocksR.log

我按照上面的操作，执行成功了。
显示了下面的信息：
Congratulations, ShadowsocksR server install completed!
Your Server IP        :your_server_ip
Your Server Port      :your_server_port
Your Password         :your_password
Your Protocol         :your_protocol
Your obfs             :your_obfs
Your Encryption Method:your_encryption_method

Welcome to visit:https://shadowsocks.be/9.html
Enjoy it!

但是怎么翻墙，我用浏览器访问油管还是不行？

**Comment by diaowenyang** [comment]
我把防火墙也关了，还是不行

**Comment by uygnef** [comment]
本地要装ssr的客户端
