### ISSUE TITLE
centos 6.5 x86 开启 TCP BBR 失败。

### ISSUE THREAD

**Issue by dongshimou** [iMeiji/shadowsocks_install#5]
执行
`rpm -Uvh http://www.elrepo.org/elrepo-release-6-6.el6.elrepo.noarch.rpm`
失败。

error：
`Retrieving http://www.elrepo.org/elrepo-release-6-6.el6.elrepo.noarch.rpm
error: Failed dependencies:
        kernel = 2.6.32 is needed by elrepo-release-6-6.el6.elrepo.noarch`

**Comment by dongshimou** [comment]
貌似是因为vps是openvz的原因。不知道这个结论是否正确。

**Comment by iMeiji** [comment]
OpenVZ不支持换内核
