### ISSUE TITLE
像Net Speeder / FinalSpeeder / 锐速 / KCP 协议 / 开启 BBR 是共同服用吗？

### ISSUE THREAD

**Issue by Kaijun** [iMeiji/shadowsocks_install#6]
是可以共用 有最佳搭配姿势？
还是说 开启一个 其他就没用啦？

**Comment by zcdll** [comment]
同问！
不过，我觉得总带宽是一定的，国际出口也就那些。。。

**Comment by iMeiji** [comment]
TCP优化 : BBR / 锐速  
UDP优化 : NS / FS / KCP  
vps是KVM就优化TCP   OpenVZ就只能靠UDP猛发包

**Comment by huangyanxiong01** [comment]
thank you very mach
