### ISSUE TITLE
求大神支招，紧急啊

### ISSUE THREAD

**Issue by theratlesnake** [iMeiji/shadowsocks_install#8]
---------- System Information ----------
 OS      : CentOS 6.8
 Arch    : x86_64 (64 Bit)
 Kernel  : 4.8.6-coreos
----------------------------------------
照着教程输入命令，提示错误，不会解决啊，本人菜鸟，求指导！！！！！

[root@4ad8f89837a0 ~]# rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
[root@4ad8f89837a0 ~]# rpm -Uvh http://www.elrepo.org/elrepo-release-6-6.el6.elrepo.noarch.rpm
Retrieving http://www.elrepo.org/elrepo-release-6-6.el6.elrepo.noarch.rpm
error: Failed dependencies:
	kernel = 2.6.32 is needed by elrepo-release-6-6.el6.elrepo.noarch

**Comment by theratlesnake** [comment]
@jzp820927  对linux真心不懂

**Comment by theratlesnake** [comment]
@jzp820927   就是在Centos6 开启 TCP BBR
https://github.com/iMeiji/shadowsocks_install/wiki/%E5%BC%80%E5%90%AFTCP-BBR%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95

**Comment by theratlesnake** [comment]
另一个安装centos7,
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
yum --enablerepo=elrepo-kernel install kernel-ml -y
执行到第三步报错：
  file /usr/share/zsh/site-functions/_systemd-nspawn from install of systemd-219-30.el7_3.6.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/share/zsh/site-functions/_systemd-run from install of systemd-219-30.el7_3.6.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/share/zsh/site-functions/_systemd-tmpfiles from install of systemd-219-30.el7_3.6.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
  file /usr/share/zsh/site-functions/_udevadm from install of systemd-219-30.el7_3.6.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64

Error Summary
-------------
file的错太长了，就没截全

**Comment by theratlesnake** [comment]
[root@33e836d95921 ~]# egrep ^menuentry /etc/grub2.cfg | cut -f 2 -d \'
grep: /etc/grub2.cfg: No such file or directory

**Comment by jzp820927** [comment]
我只用 ubuntu，centos 也不是太熟悉，等大神来回答你吧。

**Comment by theratlesnake** [comment]
@jzp820927 好吧，谢啦

**Comment by theratlesnake** [comment]
Debian 8 / Ubuntu 14

下载最新内核,最新内核查看这里
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.7/linux-image-4.9.7-040907-generic_4.9.7-040907.201702010331_amd64.deb

安装内核
dpkg -i linux-image-4.9.7*.deb

删除旧内核(可选)
dpkg -l|grep linux-image 
apt-get purge 旧内核

更新 grub 系统引导文件并重启
update-grub
reboot
------------------------------------------------------------------------------
原版我的ubuntu是4.8的，执行到这个步骤【dpkg -l|grep linux-image 】
ii  linux-image-4.9.0-040900rc8-generic   4.9.0-040900rc8.201612051443     amd64        Linux kernel image for version 4.9.0 on 64 bit x86 SMP

接着这步【apt-get purge 旧内核】怎么操作哦？

**Comment by jzp820927** [comment]
如果用 ubuntu 的话，建议用 16.04，是目前的最新 长期支持 版。
看你发出来的查询结果，显示的都是最新的内容，没有旧内核，就不用执行删除操作了。

**Comment by theratlesnake** [comment]
但是我用【uname -r】显示的还是4.8，
然后执行~# update-grub
提示错误：-bash: update-grub: command not found

linux升级真是蛋疼

**Comment by iMeiji** [comment]
可以看下这个
https://xing-zhi-love.com/index.php/440.html
我的文章并没有说支持 arch

**Comment by theratlesnake** [comment]
@iMeiji 老大你好，我是在樱花arukas上设置的，不知道你这个arch是什么哦？不好意思啊

**Comment by iMeiji** [comment]
docker 玩毛线内核啊

**Comment by theratlesnake** [comment]
我看到有人玩成功了啊，kcp和BBR都成功了
