### ISSUE TITLE
我按教程安装完以后，首页是一片空白，请教是怎么回事呢？

### ISSUE THREAD

**Issue by chinawenxu** [iMeiji/shadowsocks_install#9]
在几台主机上安装都不行，用的LNMP1.3，PHP是7，按教程走完，首页一片空白，什么都没有。。

**Comment by iMeiji** [comment]
这里不解答 sspanel 问题

**Comment by chinawenxu** [comment]
好的

iMeiji <notifications@github.com>于2017年2月16日周四 下午4:00写道：
